name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  Tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        dotnet test --configuration "Debug" BorobudurReliefStories.Core.Test/BorobudurReliefStories.Core.Test.csproj
        dotnet test --configuration "Debug" BorobudurReliefStories.UI.Test/BorobudurReliefStories.UI.Test.csproj
        dotnet test --configuration "Release" BorobudurReliefStories.Core.Test/BorobudurReliefStories.Core.Test.csproj
        dotnet test --configuration "Release" BorobudurReliefStories.UI.Test/BorobudurReliefStories.UI.Test.csproj

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build for Droid
      run: |
        nuget restore
        msbuild BorobudurReliefStories.Droid/BorobudurReliefStories.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        msbuild BorobudurReliefStories.Droid/BorobudurReliefStories.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release

  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build for iOS
      run: |
        nuget restore
        msbuild BorobudurReliefStories.iOS/BorobudurReliefStories.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        msbuild BorobudurReliefStories.iOS/BorobudurReliefStories.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
