name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  Tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        dotnet test --configuration "Debug" DR.CeritaReliefLalitavistara.Core.Test/DR.CeritaReliefLalitavistara.Core.Test.csproj
        dotnet test --configuration "Debug" DR.CeritaReliefLalitavistara.UI.Test/DR.CeritaReliefLalitavistara.UI.Test.csproj
        dotnet test --configuration "Release" DR.CeritaReliefLalitavistara.Core.Test/DR.CeritaReliefLalitavistara.Core.Test.csproj
        dotnet test --configuration "Release" DR.CeritaReliefLalitavistara.UI.Test/DR.CeritaReliefLalitavistara.UI.Test.csproj

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build for Droid
      run: |
        nuget restore
        msbuild DR.CeritaReliefLalitavistara.Droid/DR.CeritaReliefLalitavistara.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        msbuild DR.CeritaReliefLalitavistara.Droid/DR.CeritaReliefLalitavistara.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release

  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build for iOS
      run: |
        nuget restore
        msbuild DR.CeritaReliefLalitavistara.iOS/DR.CeritaReliefLalitavistara.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        msbuild DR.CeritaReliefLalitavistara.iOS/DR.CeritaReliefLalitavistara.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
